### ISSUE TITLE
Add options to put all highlights into one note/book

### ISSUE THREAD

**Issue by trungng2006** [Edo78/obsidian-koreader-sync#55]
Thank you for your wonderful plugin!!!
I think it would be nice if the plugin have an option to sync all the book highlight into a single note (each book become one note). So it wont create too many notes in my vault, and I can synthesize the note easier. May I ask if this is possible?

**Comment by Edo78** [comment]
Hi, thanks for your appreciation.

I've already tried to do something similar in #9 but sadly it would require a lot of work.

As I previously did I can suggest you to create a template for the book notes with a different dataview query.

You should follow the [doc](https://github.com/Edo78/obsidian-koreader-sync#book-view-configuration) creating a template like
~~~markdown
# Title: <%= it.data.title %>

<progress value="<%= it.metadata.percent_finished %>" max="100"> </progress>
```dataviewjs
const title = dv.current()['koreader-sync'].metadata.managed_title
dv.pages().where(n => {
return n['koreader-sync'] && n['koreader-sync'].type == 'koreader-sync-note' && n['koreader-sync'].metadata.managed_book_title == title
}).sort(p => p['koreader-sync'].data.page).forEach(p => dv.paragraph(p['koreader-sync'].data.highlight))
```
~~~

This way the query will get and show only the highlights of that book. Working with dataview you should even be able to group by chapter, showing the page of the note and so on.

Sorry but right now I don't have the time to do the requested edit and in my opinion it will not be an upgrade to the plugin because a lot of features like querying the notes to create customized views will be lost.

**Comment by trungng2006** [comment]
No need to say sorry. I appreciate that you take time to show me how to better utilize the plugin.
Thank you!

**Comment by Edo78** [comment]
You can even modify the template I just shared to add a link to the note with that highlight to some editing. Not as quick as having in the same note but can be a workaround.
Or maybe it's possibile to find a plugin that can query frtonmatter like dataview but write the result on a real note instead of a dynamic view (I'm pretty new to the whole Obsidian thing)
